### PR TITLE
bits basics

### PR DESCRIPTION
**Pull request by aryan2621**
bits basics with explanation

### CODE REVIEW

**Comment by kuspia** [comment]
hve u tried running it , it generates error on the compiler kindly fix it and then create the PR again

**Comment by aryan2621** [comment]
> hve u tried running it , it generates error on the compiler kindly fix it and then create the PR again

Obviously it will show error as this is not a specific program it is the pseudo code, it is to understand the concepts, not to produce any specific output

**Comment by kuspia** [comment]
kindly write a proper CPP code, I nvr said to write a pseudo code

**Comment by aryan2621** [comment]
> kindly write a proper CPP code, I nvr said to write a pseudo code

What you want.... A running code? Just

**Comment by kuspia** [comment]
Yes a error free cpp file written completely by you from scratch with proper comments. My goal is to make people learn completely by understanding every line.

I will read and review every line afterwards

**Pull request closed without merging**
