### PR TITLE
Add two code  Fast Fourier transform and Enumerating submasks of a bitmask 

### PR DESCRIPTION
**Pull request by Ashwanigupta9125**
Add two code  Fast Fourier transform and Enumerating submasks of a bitmask  with code explain between comment and easy to understand

### CODE REVIEW

**Comment by kuspia** [comment]
Kindly submit ur original work, the code that you write from scratch by completely understanding it 😀 that work can be appreciated.

**Comment by Ashwanigupta9125** [comment]
> Kindly submit ur original work, the code that you write from scratch by completely understanding it 😀 that work can be appreciated.
please help me. I don't understand what to correct in code 
I am a pure beginner here, so please help me so I can be a part of your repo.
( sorry to disturb u )

**Comment by kuspia** [comment]
The codes were correct but copied so u need to write the code on your own then only it will be merged

**Comment by Ashwanigupta9125** [comment]
> The codes were correct but copied so u need to write the code on your own then only it will be merged

Ohh sorry,I understand the code but due to properly organizing the code I copy it  but now I don't make ur effort of teaching new coder like us don't let to fail  and I make my own code explanation in my way and submit to u
Thank you

**Pull request closed without merging**
